

build:
  version: "5.0"

cards:
  message: "Welcome to EazyBank cards related prod APIs "
  contactDetails:
    name: "Muhammet Celik - prod Developer"
    email: "muhammetclk56@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345