services:
 accounts:
  image: "muhammetcelik56/accounts:s1"
  container_name: accounts-ms
  ports:
   - "8080:8080"
  deploy:
   resources:
    limits:
     memory: "700m"
  networks:
   - eazybank
 loans:
  image: "muhammetcelik56/loans:s1"
  container_name: loans-ms
  ports:
   - "8090:8090"
  deploy:
   resources:
    limits:
     memory: "700m"
  networks:
   - eazybank
 cards:
  image: "muhammetcelik56/cards:s1"
  container_name: cards-ms
  ports:
   - "9000:9000"
  deploy:
   resources:
    limits:
     memory: "700m" 
  networks:
   - eazybank

networks:
  eazybank:
   driver: bridge