

build:
  version: "2.0"

loans:
  message: "Welcome to EazyBank loans related QA APIs "
  contactDetails:
    name: "Muhammet Celik - QA Developer"
    email: "muhammetclk56@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345