


build:
  version: 3.0


loans:
  message: "Welcome to EazyBank loans related local APIs "
  contactDetails:
    name: "loan Doe - Developer"
    email: "loanohn@eazybank.com"
  onCallSupport:
    - (555) 550-4321
    - (555) 523-7894