

services:
  rabbit:
    image: rabbitmq:4.1-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "muhammetcelik56/configserver:s2"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: curl --fail --silent http://localhost:8071/actuator/health/readiness | grep UP || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "muhammetcelik56/accounts:s2"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=accounts
    depends_on:
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "muhammetcelik56/loans:s2"
    container_name: loans-ms
    ports:
      - "8090:8090"
    environment:
      - SPRING_APPLICATION_NAME=loans
    depends_on:
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "muhammetcelik56/cards:s2"
    container_name: cards-ms
    ports:
      - "9000:9000"
    environment:
      - SPRING_APPLICATION_NAME=cards
    depends_on:
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  eazybank:
    driver: bridge
