

server:
  port: 8090
spring:
  application:
    name: loans
  datasource:
    url: jdbc:mysql://localhost:3309/loansdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import:
    - optional:configserver:http://localhost:8071/
  profiles:
    active:
    - prod

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
